### ISSUE TITLE
Add Responsiveness for Roadmap

### ISSUE THREAD

**Issue by ramanxg** [icssc-projects/peterportal-client#130]
You are unable to see the actual 4-year planner, so you can't drag any courses into it. 

- [ ] Remove drag and drop from search to roadmap for mobile, 
  - [ ] Display search and roadmaps separately like in different tabs
  - [ ] When user clicks on a course in the search, prompt them which year/quarter they want to add it to
- [ ] Display quarters from top-down

![image](https://user-images.githubusercontent.com/9029237/153274940-0315d58b-e409-4ad0-94d3-87000a8858c7.png)
