### ISSUE TITLE
Validate Roadmaps Prerequisites

### ISSUE THREAD

**Issue by chenaaron3** [icssc-projects/peterportal-client#137]
- [x] Highlight a course card (or add a warning icon) if its prerequisites are not met
- [x] Allow users to resolve warnings. For example, if they took AP tests or transferred credits
  - [x] Store a hidden list of courses called 'transferred' that would satisfy these prerequisites
  - [x] If the user wants to dismiss a warning, prompt them to select a subset of the prerequisites to add to the transferred list
  - [x] Validating each course would cross-reference the transferred list along with the roadmap
