### ISSUE TITLE
Save Roadmap to Account

### ISSUE THREAD

**Issue by chenaaron3** [icssc-projects/peterportal-client#99]
- [x] Refactor how the roadmap is stored in state. Currently, Course Data is nested inside roadmap. Should store Course Data in separate lookup table so we don't store duplicate data in persistent storage.
  - [x] When the user adds a course, need to add the into the lookup
- [x] On roadmap load
  - [x] Get roadmap from persistent storage
  - [x] Do a bulk search to get all course data in the roadmap and store it in the lookup
- [x] On roadmap save
  - [x] Store roadmap to persistent storage
